#---------------------------------------
# generating read-counts-per gene 
cd /work/08717/dmflores/ls6/db/amil/star_index
## The geneInfo.tab generated by STAR has the two column identifiers
tail -n +2 geneInfo.tab | awk '{$3=""; print $0}' | sed 's/  */ /g'  > ../amilGenes.txt 

TAB="/work/08717/dmflores/ls6/db/amil/amilGenes.txt"

## 
cd /scratch/08717/dmflores/LarvalGE/AMIL/TrimmedFQ

conda activate genomeenv
# counting hits per isogroup:
samcount_launch_bt2.pl '\.sam' $TAB > sc
# execute all commands in 'sc' file

ls6_launcher_creator.py -j sc -n sc -t 02:00:00 -a IBN21018 -e dmflores@utexas.edu 

sbatch sc.slurm

# assembling all counts into a single table:
expression_compiler.pl *.sam.counts > allcounts.txt


#On Local Computer
cd /Users/daisyflores/Desktop/DLAB
scp dmflores@ls6.tacc.utexas.edu:/scratch/08717/dmflores/LarvalGE/TrimmedFQ/DLAB/\*txt .



samtools view W4-3_S168_L002_R1_001.trim.sam

